.Dd March 08, 2020
.Dt PLAYONBSD-CLI 1
.Os
.Sh NAME
.Nm playonbsd-cli
.Nd manage games on OpenBSD
.Sh SYNOPSIS
playonbsd-cli
.Oo
.Oc
.Oo
.Oc
.Oo
.Oc
.Oo
.Oc
-hv-manMODE\&...
.Pp
Modes:
.br
help
.br
init
.br
install
.br
run
.br
setup
.br
uninstall
.Sh OPTIONS
.Bl -tag -width Ds
.It Sy -h/--help
This message.
.It Sy -v/--version
Print version string.
.El
.Sh DESCRIPTION
.Sy This program
provides several modes to set up and run games, and manage your game
library.
